package org.mrpaulwoods.employee

import org.mrpaulwoods.employee.payroll.Salary
import org.mrpaulwoods.employee.payroll.SalaryRepository
import org.mrpaulwoods.employee.personnel.Personnel
import org.mrpaulwoods.employee.personnel.PersonnelRepository
import org.mrpaulwoods.employee.profile.Profile
import org.mrpaulwoods.employee.profile.ProfileRepository
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component

import javax.annotation.PostConstruct

/**
 * Created on 3/7/2016.
 */
@Component
class Bootstrap {

    private final PersonnelRepository personnelRepository
    private final ProfileRepository profileRepository
    private final SalaryRepository salaryRepository

    @Autowired
    Bootstrap(PersonnelRepository personnelRepository,
              ProfileRepository profileRepository,
              SalaryRepository salaryRepository) {
        this.personnelRepository = personnelRepository
        this.profileRepository = profileRepository
        this.salaryRepository = salaryRepository
    }

    @PostConstruct
    def init() {
        initPersonnel()
        initProfile()
        initSalary()
    }

    def initPersonnel() {
        personnelRepository.save new Personnel(firstName:"Wylie", lastName:"Lott")
        personnelRepository.save new Personnel(firstName:"Aimee", lastName:"Fleming")
        personnelRepository.save new Personnel(firstName:"Cassady", lastName:"Sparks")
        personnelRepository.save new Personnel(firstName:"Mari", lastName:"Zamora")
        personnelRepository.save new Personnel(firstName:"Herman", lastName:"Paul")
        personnelRepository.save new Personnel(firstName:"Vance", lastName:"Chang")
        personnelRepository.save new Personnel(firstName:"Justine", lastName:"Saunders")
        personnelRepository.save new Personnel(firstName:"Myles", lastName:"Bray")
        personnelRepository.save new Personnel(firstName:"Janna", lastName:"Moran")
        personnelRepository.save new Personnel(firstName:"Skyler", lastName:"Macias")
        personnelRepository.save new Personnel(firstName:"Indigo", lastName:"Vinson")
        personnelRepository.save new Personnel(firstName:"Kai", lastName:"Acosta")
        personnelRepository.save new Personnel(firstName:"Victoria", lastName:"Montoya")
        personnelRepository.save new Personnel(firstName:"Palmer", lastName:"Slater")
        personnelRepository.save new Personnel(firstName:"Kelly", lastName:"Burnett")
        personnelRepository.save new Personnel(firstName:"Malachi", lastName:"Chen")
        personnelRepository.save new Personnel(firstName:"Craig", lastName:"Richardson")
        personnelRepository.save new Personnel(firstName:"Bevis", lastName:"Baldwin")
        personnelRepository.save new Personnel(firstName:"Colton", lastName:"Moss")
        personnelRepository.save new Personnel(firstName:"Ursula", lastName:"Moses")
        personnelRepository.save new Personnel(firstName:"Avye", lastName:"Casey")
        personnelRepository.save new Personnel(firstName:"Brenda", lastName:"Hogan")
        personnelRepository.save new Personnel(firstName:"Malcolm", lastName:"Mann")
        personnelRepository.save new Personnel(firstName:"Camden", lastName:"Foley")
        personnelRepository.save new Personnel(firstName:"Alice", lastName:"Salazar")
        personnelRepository.save new Personnel(firstName:"Martena", lastName:"Vazquez")
        personnelRepository.save new Personnel(firstName:"Iliana", lastName:"Harrell")
        personnelRepository.save new Personnel(firstName:"Inez", lastName:"Knight")
        personnelRepository.save new Personnel(firstName:"Devin", lastName:"Horne")
        personnelRepository.save new Personnel(firstName:"Vaughan", lastName:"Glover")
        personnelRepository.save new Personnel(firstName:"Preston", lastName:"Barr")
        personnelRepository.save new Personnel(firstName:"Samson", lastName:"Buckner")
        personnelRepository.save new Personnel(firstName:"Garrison", lastName:"Rosales")
        personnelRepository.save new Personnel(firstName:"Nora", lastName:"Huffman")
        personnelRepository.save new Personnel(firstName:"Whitney", lastName:"Serrano")
        personnelRepository.save new Personnel(firstName:"Chester", lastName:"May")
        personnelRepository.save new Personnel(firstName:"Thomas", lastName:"Watkins")
        personnelRepository.save new Personnel(firstName:"Myra", lastName:"Franklin")
        personnelRepository.save new Personnel(firstName:"Rylee", lastName:"Davenport")
        personnelRepository.save new Personnel(firstName:"Cora", lastName:"Richard")
        personnelRepository.save new Personnel(firstName:"Julie", lastName:"Allison")
        personnelRepository.save new Personnel(firstName:"Reed", lastName:"Shaw")
        personnelRepository.save new Personnel(firstName:"Macey", lastName:"Castaneda")
        personnelRepository.save new Personnel(firstName:"Reese", lastName:"Figueroa")
        personnelRepository.save new Personnel(firstName:"Trevor", lastName:"Mcdowell")
        personnelRepository.save new Personnel(firstName:"Kay", lastName:"Miranda")
        personnelRepository.save new Personnel(firstName:"Devin", lastName:"Curtis")
        personnelRepository.save new Personnel(firstName:"Lesley", lastName:"Ward")
        personnelRepository.save new Personnel(firstName:"Rhea", lastName:"Rowe")
        personnelRepository.save new Personnel(firstName:"Alexa", lastName:"Savage")
        personnelRepository.save new Personnel(firstName:"Scarlet", lastName:"Washington")
        personnelRepository.save new Personnel(firstName:"Hayes", lastName:"Meyer")
        personnelRepository.save new Personnel(firstName:"Camden", lastName:"Frederick")
        personnelRepository.save new Personnel(firstName:"Kiara", lastName:"Mcintosh")
        personnelRepository.save new Personnel(firstName:"Leo", lastName:"Conrad")
        personnelRepository.save new Personnel(firstName:"Brooke", lastName:"Daugherty")
        personnelRepository.save new Personnel(firstName:"Naomi", lastName:"Weiss")
        personnelRepository.save new Personnel(firstName:"Ella", lastName:"Taylor")
        personnelRepository.save new Personnel(firstName:"David", lastName:"Houston")
        personnelRepository.save new Personnel(firstName:"Edward", lastName:"Norris")
        personnelRepository.save new Personnel(firstName:"Quincy", lastName:"Giles")
        personnelRepository.save new Personnel(firstName:"Bradley", lastName:"Callahan")
        personnelRepository.save new Personnel(firstName:"Curran", lastName:"Terrell")
        personnelRepository.save new Personnel(firstName:"Yvette", lastName:"Gray")
        personnelRepository.save new Personnel(firstName:"Ronan", lastName:"Cochran")
        personnelRepository.save new Personnel(firstName:"Holmes", lastName:"Boyer")
        personnelRepository.save new Personnel(firstName:"Ezekiel", lastName:"Mcleod")
        personnelRepository.save new Personnel(firstName:"Lana", lastName:"Huber")
        personnelRepository.save new Personnel(firstName:"Gary", lastName:"Woodward")
        personnelRepository.save new Personnel(firstName:"Signe", lastName:"Moses")
        personnelRepository.save new Personnel(firstName:"Murphy", lastName:"Combs")
        personnelRepository.save new Personnel(firstName:"Ivory", lastName:"Burks")
        personnelRepository.save new Personnel(firstName:"Doris", lastName:"Higgins")
        personnelRepository.save new Personnel(firstName:"Quon", lastName:"Scott")
        personnelRepository.save new Personnel(firstName:"Vivien", lastName:"Kemp")
        personnelRepository.save new Personnel(firstName:"Bertha", lastName:"Briggs")
        personnelRepository.save new Personnel(firstName:"Chadwick", lastName:"Barnes")
        personnelRepository.save new Personnel(firstName:"Gil", lastName:"Burnett")
        personnelRepository.save new Personnel(firstName:"Juliet", lastName:"Wooten")
        personnelRepository.save new Personnel(firstName:"Hasad", lastName:"Ryan")
        personnelRepository.save new Personnel(firstName:"Geraldine", lastName:"Mitchell")
        personnelRepository.save new Personnel(firstName:"Athena", lastName:"Cain")
        personnelRepository.save new Personnel(firstName:"Mannix", lastName:"Singleton")
        personnelRepository.save new Personnel(firstName:"Theodore", lastName:"Meyer")
        personnelRepository.save new Personnel(firstName:"Claire", lastName:"Rocha")
        personnelRepository.save new Personnel(firstName:"Libby", lastName:"Wells")
        personnelRepository.save new Personnel(firstName:"Kessie", lastName:"Buchanan")
        personnelRepository.save new Personnel(firstName:"Cleo", lastName:"Tyler")
        personnelRepository.save new Personnel(firstName:"Tyrone", lastName:"Blair")
        personnelRepository.save new Personnel(firstName:"Sylvester", lastName:"Hayden")
        personnelRepository.save new Personnel(firstName:"Sarah", lastName:"Long")
        personnelRepository.save new Personnel(firstName:"Evangeline", lastName:"Flores")
        personnelRepository.save new Personnel(firstName:"Hamish", lastName:"Collins")
        personnelRepository.save new Personnel(firstName:"Walker", lastName:"Snider")
        personnelRepository.save new Personnel(firstName:"Maggie", lastName:"Burton")
        personnelRepository.save new Personnel(firstName:"Lunea", lastName:"Marsh")
        personnelRepository.save new Personnel(firstName:"Zane", lastName:"Cameron")
        personnelRepository.save new Personnel(firstName:"Risa", lastName:"Nixon")
        personnelRepository.save new Personnel(firstName:"Madison", lastName:"Phillips")
        personnelRepository.save new Personnel(firstName:"Donovan", lastName:"Aguirre")
    }

    def initProfile() {
        profileRepository.save new Profile(person: personnelRepository.getOne(1L), street: "P.O. Box 994, 5966 Commodo Av.", city: "Owensboro", state: "Kentucky", zip: "59978")
        profileRepository.save new Profile(person: personnelRepository.getOne(2L), street: "Ap #675-4091 Cras Rd.", city: "Pike Creek", state: "Delaware", zip: "19612")
        profileRepository.save new Profile(person: personnelRepository.getOne(3L), street: "Ap #651-7033 Diam Ave", city: "Omaha", state: "Nebraska", zip: "51467")
        profileRepository.save new Profile(person: personnelRepository.getOne(4L), street: "1555 Sed Ave", city: "Chicago", state: "Illinois", zip: "77524")
        profileRepository.save new Profile(person: personnelRepository.getOne(5L), street: "5988 Morbi Rd.", city: "Chandler", state: "AZ", zip: "85669")
        profileRepository.save new Profile(person: personnelRepository.getOne(6L), street: "Ap #892-3469 Lobortis. St.", city: "Lewiston", state: "Maine", zip: "38829")
        profileRepository.save new Profile(person: personnelRepository.getOne(7L), street: "2078 Vel, Rd.", city: "Tucson", state: "AZ", zip: "85225")
        profileRepository.save new Profile(person: personnelRepository.getOne(8L), street: "841-3562 Gravida. Rd.", city: "Austin", state: "TX", zip: "53227")
        profileRepository.save new Profile(person: personnelRepository.getOne(9L), street: "P.O. Box 478, 4716 Turpis. St.", city: "Columbus", state: "Ohio", zip: "56821")
        profileRepository.save new Profile(person: personnelRepository.getOne(10L), street: "P.O. Box 479, 1317 Justo Street", city: "Cambridge", state: "MA", zip: "49317")
        profileRepository.save new Profile(person: personnelRepository.getOne(11L), street: "4881 Non, Av.", city: "Biloxi", state: "MS", zip: "34468")
        profileRepository.save new Profile(person: personnelRepository.getOne(12L), street: "615-2692 Ut, Av.", city: "Jackson", state: "MS", zip: "81774")
        profileRepository.save new Profile(person: personnelRepository.getOne(13L), street: "Ap #231-5432 Scelerisque Avenue", city: "Olathe", state: "KS", zip: "13874")
        profileRepository.save new Profile(person: personnelRepository.getOne(14L), street: "565-933 Cras Av.", city: "Butte", state: "MT", zip: "13206")
        profileRepository.save new Profile(person: personnelRepository.getOne(15L), street: "P.O. Box 645, 3346 Donec St.", city: "Anchorage", state: "AK", zip: "99812")
        profileRepository.save new Profile(person: personnelRepository.getOne(16L), street: "935-1430 Donec Road", city: "Omaha", state: "Nebraska", zip: "49009")
        profileRepository.save new Profile(person: personnelRepository.getOne(17L), street: "3324 Fringilla Ave", city: "Anchorage", state: "AK", zip: "99659")
        profileRepository.save new Profile(person: personnelRepository.getOne(18L), street: "2340 Velit. St.", city: "Fort Wayne", state: "IN", zip: "64205")
        profileRepository.save new Profile(person: personnelRepository.getOne(19L), street: "2421 Vitae Ave", city: "Lewiston", state: "ME", zip: "33812")
        profileRepository.save new Profile(person: personnelRepository.getOne(20L), street: "P.O. Box 742, 5236 Libero Avenue", city: "Warren", state: "Michigan", zip: "78281")
        profileRepository.save new Profile(person: personnelRepository.getOne(21L), street: "154 Justo Rd.", city: "Pittsburgh", state: "Pennsylvania", zip: "71526")
        profileRepository.save new Profile(person: personnelRepository.getOne(22L), street: "Ap #526-2726 Purus Road", city: "Metairie", state: "LA", zip: "43621")
        profileRepository.save new Profile(person: personnelRepository.getOne(23L), street: "7329 Malesuada Rd.", city: "Fort Smith", state: "AR", zip: "72058")
        profileRepository.save new Profile(person: personnelRepository.getOne(24L), street: "Ap #288-8853 Nam Road", city: "Clarksville", state: "TN", zip: "70823")
        profileRepository.save new Profile(person: personnelRepository.getOne(25L), street: "7529 Turpis. Street", city: "Richmond", state: "Virginia", zip: "49504")
        profileRepository.save new Profile(person: personnelRepository.getOne(26L), street: "P.O. Box 343, 6278 Dolor Street", city: "Springfield", state: "MO", zip: "79391")
        profileRepository.save new Profile(person: personnelRepository.getOne(27L), street: "4580 Aliquet Street", city: "Meridian", state: "ID", zip: "39638")
        profileRepository.save new Profile(person: personnelRepository.getOne(28L), street: "391-7877 Eu St.", city: "Rochester", state: "Minnesota", zip: "48444")
        profileRepository.save new Profile(person: personnelRepository.getOne(29L), street: "3964 Elementum Avenue", city: "Juneau", state: "AK", zip: "99713")
        profileRepository.save new Profile(person: personnelRepository.getOne(30L), street: "Ap #862-4112 Imperdiet Street", city: "Stamford", state: "CT", zip: "48647")
        profileRepository.save new Profile(person: personnelRepository.getOne(31L), street: "2526 Et, Street", city: "Ketchikan", state: "AK", zip: "99951")
        profileRepository.save new Profile(person: personnelRepository.getOne(32L), street: "4145 Quam. Street", city: "Auburn", state: "ME", zip: "60487")
        profileRepository.save new Profile(person: personnelRepository.getOne(33L), street: "838-6593 Nullam St.", city: "Overland Park", state: "Kansas", zip: "41109")
        profileRepository.save new Profile(person: personnelRepository.getOne(34L), street: "113-3006 Lacus. Road", city: "Springdale", state: "AR", zip: "72243")
        profileRepository.save new Profile(person: personnelRepository.getOne(35L), street: "Ap #439-6686 Hendrerit Road", city: "San Jose", state: "CA", zip: "93819")
        profileRepository.save new Profile(person: personnelRepository.getOne(36L), street: "298-5091 Mauris Street", city: "Frankfort", state: "Kentucky", zip: "44692")
        profileRepository.save new Profile(person: personnelRepository.getOne(37L), street: "671-8490 Nulla Avenue", city: "Jonesboro", state: "AR", zip: "71426")
        profileRepository.save new Profile(person: personnelRepository.getOne(38L), street: "Ap #812-5486 In Ave", city: "Rockville", state: "MD", zip: "15264")
        profileRepository.save new Profile(person: personnelRepository.getOne(39L), street: "572-2104 Lorem, Rd.", city: "Fairbanks", state: "AK", zip: "99690")
        profileRepository.save new Profile(person: personnelRepository.getOne(40L), street: "Ap #920-5657 Fusce Avenue", city: "Kansas City", state: "Kansas", zip: "71642")
        profileRepository.save new Profile(person: personnelRepository.getOne(41L), street: "P.O. Box 256, 7989 Euismod Street", city: "Fort Smith", state: "Arkansas", zip: "71048")
        profileRepository.save new Profile(person: personnelRepository.getOne(42L), street: "P.O. Box 486, 1382 Nunc Av.", city: "Jonesboro", state: "Arkansas", zip: "71981")
        profileRepository.save new Profile(person: personnelRepository.getOne(43L), street: "153-9401 Tincidunt St.", city: "Salem", state: "Oregon", zip: "25094")
        profileRepository.save new Profile(person: personnelRepository.getOne(44L), street: "Ap #608-8017 Lectus Road", city: "San Diego", state: "CA", zip: "93314")
        profileRepository.save new Profile(person: personnelRepository.getOne(45L), street: "3426 Turpis. Av.", city: "Lexington", state: "Kentucky", zip: "20893")
        profileRepository.save new Profile(person: personnelRepository.getOne(46L), street: "P.O. Box 165, 2614 Ante Road", city: "Vancouver", state: "WA", zip: "12133")
        profileRepository.save new Profile(person: personnelRepository.getOne(47L), street: "9563 Eu Av.", city: "Cedar Rapids", state: "IA", zip: "98658")
        profileRepository.save new Profile(person: personnelRepository.getOne(48L), street: "P.O. Box 298, 6912 Suscipit, Rd.", city: "Baltimore", state: "Maryland", zip: "86700")
        profileRepository.save new Profile(person: personnelRepository.getOne(49L), street: "7042 Enim, St.", city: "Burlington", state: "VT", zip: "27607")
        profileRepository.save new Profile(person: personnelRepository.getOne(50L), street: "158-487 Sit Ave", city: "Kailua", state: "HI", zip: "20968")
        profileRepository.save new Profile(person: personnelRepository.getOne(51L), street: "Ap #259-1838 Neque. Road", city: "Seattle", state: "Washington", zip: "45205")
        profileRepository.save new Profile(person: personnelRepository.getOne(52L), street: "6952 Nulla. Avenue", city: "Juneau", state: "AK", zip: "99694")
        profileRepository.save new Profile(person: personnelRepository.getOne(53L), street: "Ap #107-2451 Inceptos Rd.", city: "Bellevue", state: "Nebraska", zip: "92393")
        profileRepository.save new Profile(person: personnelRepository.getOne(54L), street: "Ap #851-8171 Pede. Road", city: "Independence", state: "Missouri", zip: "12775")
        profileRepository.save new Profile(person: personnelRepository.getOne(55L), street: "P.O. Box 451, 7545 Sit Road", city: "Salem", state: "OR", zip: "95154")
        profileRepository.save new Profile(person: personnelRepository.getOne(56L), street: "185-1027 Massa Street", city: "Cheyenne", state: "WY", zip: "11344")
        profileRepository.save new Profile(person: personnelRepository.getOne(57L), street: "704-4656 Dictum Ave", city: "Grand Rapids", state: "Michigan", zip: "72281")
        profileRepository.save new Profile(person: personnelRepository.getOne(58L), street: "Ap #195-367 Ipsum Rd.", city: "Tuscaloosa", state: "AL", zip: "36971")
        profileRepository.save new Profile(person: personnelRepository.getOne(59L), street: "P.O. Box 911, 3939 Aliquet Rd.", city: "Covington", state: "KY", zip: "94553")
        profileRepository.save new Profile(person: personnelRepository.getOne(60L), street: "866-5985 Ac St.", city: "Aurora", state: "Illinois", zip: "43121")
        profileRepository.save new Profile(person: personnelRepository.getOne(61L), street: "P.O. Box 636, 7212 Tellus. St.", city: "Waterbury", state: "Connecticut", zip: "22887")
        profileRepository.save new Profile(person: personnelRepository.getOne(62L), street: "846-2249 Egestas Street", city: "Madison", state: "Wisconsin", zip: "67027")
        profileRepository.save new Profile(person: personnelRepository.getOne(63L), street: "Ap #963-7720 Varius. Avenue", city: "Portland", state: "Maine", zip: "43247")
        profileRepository.save new Profile(person: personnelRepository.getOne(64L), street: "P.O. Box 667, 9927 Ac, Street", city: "Milwaukee", state: "WI", zip: "34331")
        profileRepository.save new Profile(person: personnelRepository.getOne(65L), street: "Ap #134-5251 Diam Avenue", city: "Dallas", state: "Texas", zip: "22843")
        profileRepository.save new Profile(person: personnelRepository.getOne(66L), street: "P.O. Box 433, 3736 Amet Rd.", city: "Wichita", state: "Kansas", zip: "64565")
        profileRepository.save new Profile(person: personnelRepository.getOne(67L), street: "986 Phasellus Avenue", city: "Olympia", state: "Washington", zip: "80324")
        profileRepository.save new Profile(person: personnelRepository.getOne(68L), street: "P.O. Box 266, 4995 Lorem Street", city: "Frederick", state: "Maryland", zip: "19654")
        profileRepository.save new Profile(person: personnelRepository.getOne(69L), street: "274-8394 Lectus Avenue", city: "Detroit", state: "MI", zip: "22487")
        profileRepository.save new Profile(person: personnelRepository.getOne(70L), street: "889-5694 Mi, Rd.", city: "Detroit", state: "MI", zip: "22985")
        profileRepository.save new Profile(person: personnelRepository.getOne(71L), street: "Ap #373-100 Molestie Ave", city: "Savannah", state: "GA", zip: "92164")
        profileRepository.save new Profile(person: personnelRepository.getOne(72L), street: "802-7034 Lorem Street", city: "Frederick", state: "MD", zip: "12225")
        profileRepository.save new Profile(person: personnelRepository.getOne(73L), street: "P.O. Box 493, 4076 Eget Rd.", city: "St. Petersburg", state: "FL", zip: "78903")
        profileRepository.save new Profile(person: personnelRepository.getOne(74L), street: "P.O. Box 988, 5690 Libero Road", city: "Lansing", state: "Michigan", zip: "88187")
        profileRepository.save new Profile(person: personnelRepository.getOne(75L), street: "397-8919 Aenean Avenue", city: "Savannah", state: "GA", zip: "96447")
        profileRepository.save new Profile(person: personnelRepository.getOne(76L), street: "6784 Ornare Avenue", city: "Lansing", state: "MI", zip: "60190")
        profileRepository.save new Profile(person: personnelRepository.getOne(77L), street: "Ap #665-990 Erat Rd.", city: "Toledo", state: "Ohio", zip: "92301")
        profileRepository.save new Profile(person: personnelRepository.getOne(78L), street: "9783 Mauris Avenue", city: "Baltimore", state: "MD", zip: "35600")
        profileRepository.save new Profile(person: personnelRepository.getOne(79L), street: "Ap #648-4531 Felis Avenue", city: "Racine", state: "WI", zip: "74468")
        profileRepository.save new Profile(person: personnelRepository.getOne(80L), street: "Ap #591-3026 Orci Av.", city: "Fort Smith", state: "Arkansas", zip: "71418")
        profileRepository.save new Profile(person: personnelRepository.getOne(81L), street: "Ap #125-6213 Luctus, Av.", city: "Little Rock", state: "AR", zip: "72031")
        profileRepository.save new Profile(person: personnelRepository.getOne(82L), street: "729-4864 Adipiscing Av.", city: "Owensboro", state: "Kentucky", zip: "48726")
        profileRepository.save new Profile(person: personnelRepository.getOne(83L), street: "P.O. Box 767, 9816 Id, Rd.", city: "Fort Wayne", state: "Indiana", zip: "12195")
        profileRepository.save new Profile(person: personnelRepository.getOne(84L), street: "P.O. Box 535, 4083 Nunc Ave", city: "Hartford", state: "Connecticut", zip: "51268")
        profileRepository.save new Profile(person: personnelRepository.getOne(85L), street: "P.O. Box 599, 7503 Lorem Rd.", city: "Southaven", state: "Mississippi", zip: "17709")
        profileRepository.save new Profile(person: personnelRepository.getOne(86L), street: "Ap #258-8219 Montes, Av.", city: "Pike Creek", state: "Delaware", zip: "30842")
        profileRepository.save new Profile(person: personnelRepository.getOne(87L), street: "263-966 Natoque Rd.", city: "Seattle", state: "WA", zip: "43196")
        profileRepository.save new Profile(person: personnelRepository.getOne(88L), street: "3398 Morbi Rd.", city: "Fresno", state: "California", zip: "94304")
        profileRepository.save new Profile(person: personnelRepository.getOne(89L), street: "P.O. Box 363, 7552 Enim, St.", city: "Houston", state: "TX", zip: "62144")
        profileRepository.save new Profile(person: personnelRepository.getOne(90L), street: "P.O. Box 909, 5933 Aliquam St.", city: "Auburn", state: "Maine", zip: "23382")
        profileRepository.save new Profile(person: personnelRepository.getOne(91L), street: "8478 Mi Rd.", city: "Portland", state: "Maine", zip: "95578")
        profileRepository.save new Profile(person: personnelRepository.getOne(92L), street: "P.O. Box 137, 3646 Eget Rd.", city: "Sioux City", state: "Iowa", zip: "66483")
        profileRepository.save new Profile(person: personnelRepository.getOne(93L), street: "P.O. Box 313, 267 In, St.", city: "College", state: "Alaska", zip: "99629")
        profileRepository.save new Profile(person: personnelRepository.getOne(94L), street: "3700 Turpis Avenue", city: "Toledo", state: "Ohio", zip: "22133")
        profileRepository.save new Profile(person: personnelRepository.getOne(95L), street: "728-6469 Vel Avenue", city: "Nashville", state: "TN", zip: "86410")
        profileRepository.save new Profile(person: personnelRepository.getOne(96L), street: "772 Non Av.", city: "Montpelier", state: "VT", zip: "69943")
        profileRepository.save new Profile(person: personnelRepository.getOne(97L), street: "Ap #934-505 Dolor. Ave", city: "Kapolei", state: "Hawaii", zip: "48363")
        profileRepository.save new Profile(person: personnelRepository.getOne(98L), street: "794-6243 A, Avenue", city: "Helena", state: "MT", zip: "13601")
        profileRepository.save new Profile(person: personnelRepository.getOne(99L), street: "267-9868 A, Road", city: "Spokane", state: "WA", zip: "30961")
        profileRepository.save new Profile(person: personnelRepository.getOne(100L), street: "1992 Proin Ave", city: "Tuscaloosa", state: "AL", zip: "35280")
    }

    def initSalary() {
        salaryRepository.save new Salary(person: personnelRepository.getOne(1L), salary: 102147)
        salaryRepository.save new Salary(person: personnelRepository.getOne(2L), salary: 139053)
        salaryRepository.save new Salary(person: personnelRepository.getOne(3L), salary: 97039)
        salaryRepository.save new Salary(person: personnelRepository.getOne(4L), salary: 118524)
        salaryRepository.save new Salary(person: personnelRepository.getOne(5L), salary: 54366)
        salaryRepository.save new Salary(person: personnelRepository.getOne(6L), salary: 77340)
        salaryRepository.save new Salary(person: personnelRepository.getOne(7L), salary: 53381)
        salaryRepository.save new Salary(person: personnelRepository.getOne(8L), salary: 85728)
        salaryRepository.save new Salary(person: personnelRepository.getOne(9L), salary: 71669)
        salaryRepository.save new Salary(person: personnelRepository.getOne(10L), salary: 118095)
        salaryRepository.save new Salary(person: personnelRepository.getOne(11L), salary: 77589)
        salaryRepository.save new Salary(person: personnelRepository.getOne(12L), salary: 67963)
        salaryRepository.save new Salary(person: personnelRepository.getOne(13L), salary: 111354)
        salaryRepository.save new Salary(person: personnelRepository.getOne(14L), salary: 94431)
        salaryRepository.save new Salary(person: personnelRepository.getOne(15L), salary: 63787)
        salaryRepository.save new Salary(person: personnelRepository.getOne(16L), salary: 117927)
        salaryRepository.save new Salary(person: personnelRepository.getOne(17L), salary: 97433)
        salaryRepository.save new Salary(person: personnelRepository.getOne(18L), salary: 66123)
        salaryRepository.save new Salary(person: personnelRepository.getOne(19L), salary: 85584)
        salaryRepository.save new Salary(person: personnelRepository.getOne(20L), salary: 82831)
        salaryRepository.save new Salary(person: personnelRepository.getOne(21L), salary: 102509)
        salaryRepository.save new Salary(person: personnelRepository.getOne(22L), salary: 59204)
        salaryRepository.save new Salary(person: personnelRepository.getOne(23L), salary: 73161)
        salaryRepository.save new Salary(person: personnelRepository.getOne(24L), salary: 52796)
        salaryRepository.save new Salary(person: personnelRepository.getOne(25L), salary: 79243)
        salaryRepository.save new Salary(person: personnelRepository.getOne(26L), salary: 122586)
        salaryRepository.save new Salary(person: personnelRepository.getOne(27L), salary: 71824)
        salaryRepository.save new Salary(person: personnelRepository.getOne(28L), salary: 145293)
        salaryRepository.save new Salary(person: personnelRepository.getOne(29L), salary: 87989)
        salaryRepository.save new Salary(person: personnelRepository.getOne(30L), salary: 79499)
        salaryRepository.save new Salary(person: personnelRepository.getOne(31L), salary: 133298)
        salaryRepository.save new Salary(person: personnelRepository.getOne(32L), salary: 148023)
        salaryRepository.save new Salary(person: personnelRepository.getOne(33L), salary: 111433)
        salaryRepository.save new Salary(person: personnelRepository.getOne(34L), salary: 85508)
        salaryRepository.save new Salary(person: personnelRepository.getOne(35L), salary: 117861)
        salaryRepository.save new Salary(person: personnelRepository.getOne(36L), salary: 61369)
        salaryRepository.save new Salary(person: personnelRepository.getOne(37L), salary: 111955)
        salaryRepository.save new Salary(person: personnelRepository.getOne(38L), salary: 85320)
        salaryRepository.save new Salary(person: personnelRepository.getOne(39L), salary: 98596)
        salaryRepository.save new Salary(person: personnelRepository.getOne(40L), salary: 117049)
        salaryRepository.save new Salary(person: personnelRepository.getOne(41L), salary: 58250)
        salaryRepository.save new Salary(person: personnelRepository.getOne(42L), salary: 86089)
        salaryRepository.save new Salary(person: personnelRepository.getOne(43L), salary: 77002)
        salaryRepository.save new Salary(person: personnelRepository.getOne(44L), salary: 112749)
        salaryRepository.save new Salary(person: personnelRepository.getOne(45L), salary: 134934)
        salaryRepository.save new Salary(person: personnelRepository.getOne(46L), salary: 135862)
        salaryRepository.save new Salary(person: personnelRepository.getOne(47L), salary: 93387)
        salaryRepository.save new Salary(person: personnelRepository.getOne(48L), salary: 136651)
        salaryRepository.save new Salary(person: personnelRepository.getOne(49L), salary: 88795)
        salaryRepository.save new Salary(person: personnelRepository.getOne(50L), salary: 53220)
        salaryRepository.save new Salary(person: personnelRepository.getOne(51L), salary: 91195)
        salaryRepository.save new Salary(person: personnelRepository.getOne(52L), salary: 65237)
        salaryRepository.save new Salary(person: personnelRepository.getOne(53L), salary: 79243)
        salaryRepository.save new Salary(person: personnelRepository.getOne(54L), salary: 79876)
        salaryRepository.save new Salary(person: personnelRepository.getOne(55L), salary: 137255)
        salaryRepository.save new Salary(person: personnelRepository.getOne(56L), salary: 140739)
        salaryRepository.save new Salary(person: personnelRepository.getOne(57L), salary: 55836)
        salaryRepository.save new Salary(person: personnelRepository.getOne(58L), salary: 122526)
        salaryRepository.save new Salary(person: personnelRepository.getOne(59L), salary: 74924)
        salaryRepository.save new Salary(person: personnelRepository.getOne(60L), salary: 60168)
        salaryRepository.save new Salary(person: personnelRepository.getOne(61L), salary: 101806)
        salaryRepository.save new Salary(person: personnelRepository.getOne(62L), salary: 59406)
        salaryRepository.save new Salary(person: personnelRepository.getOne(63L), salary: 113827)
        salaryRepository.save new Salary(person: personnelRepository.getOne(64L), salary: 96779)
        salaryRepository.save new Salary(person: personnelRepository.getOne(65L), salary: 95249)
        salaryRepository.save new Salary(person: personnelRepository.getOne(66L), salary: 104626)
        salaryRepository.save new Salary(person: personnelRepository.getOne(67L), salary: 99216)
        salaryRepository.save new Salary(person: personnelRepository.getOne(68L), salary: 95376)
        salaryRepository.save new Salary(person: personnelRepository.getOne(69L), salary: 136511)
        salaryRepository.save new Salary(person: personnelRepository.getOne(70L), salary: 60480)
        salaryRepository.save new Salary(person: personnelRepository.getOne(71L), salary: 54723)
        salaryRepository.save new Salary(person: personnelRepository.getOne(72L), salary: 91995)
        salaryRepository.save new Salary(person: personnelRepository.getOne(73L), salary: 57181)
        salaryRepository.save new Salary(person: personnelRepository.getOne(74L), salary: 132066)
        salaryRepository.save new Salary(person: personnelRepository.getOne(75L), salary: 90879)
        salaryRepository.save new Salary(person: personnelRepository.getOne(76L), salary: 148722)
        salaryRepository.save new Salary(person: personnelRepository.getOne(77L), salary: 136092)
        salaryRepository.save new Salary(person: personnelRepository.getOne(78L), salary: 142997)
        salaryRepository.save new Salary(person: personnelRepository.getOne(79L), salary: 102582)
        salaryRepository.save new Salary(person: personnelRepository.getOne(80L), salary: 142907)
        salaryRepository.save new Salary(person: personnelRepository.getOne(81L), salary: 98572)
        salaryRepository.save new Salary(person: personnelRepository.getOne(82L), salary: 101707)
        salaryRepository.save new Salary(person: personnelRepository.getOne(83L), salary: 113722)
        salaryRepository.save new Salary(person: personnelRepository.getOne(84L), salary: 56845)
        salaryRepository.save new Salary(person: personnelRepository.getOne(85L), salary: 121609)
        salaryRepository.save new Salary(person: personnelRepository.getOne(86L), salary: 136577)
        salaryRepository.save new Salary(person: personnelRepository.getOne(87L), salary: 91618)
        salaryRepository.save new Salary(person: personnelRepository.getOne(88L), salary: 147560)
        salaryRepository.save new Salary(person: personnelRepository.getOne(89L), salary: 118597)
        salaryRepository.save new Salary(person: personnelRepository.getOne(90L), salary: 60046)
        salaryRepository.save new Salary(person: personnelRepository.getOne(91L), salary: 51910)
        salaryRepository.save new Salary(person: personnelRepository.getOne(92L), salary: 85161)
        salaryRepository.save new Salary(person: personnelRepository.getOne(93L), salary: 109918)
        salaryRepository.save new Salary(person: personnelRepository.getOne(94L), salary: 128636)
        salaryRepository.save new Salary(person: personnelRepository.getOne(95L), salary: 103669)
        salaryRepository.save new Salary(person: personnelRepository.getOne(96L), salary: 102029)
        salaryRepository.save new Salary(person: personnelRepository.getOne(97L), salary: 121089)
        salaryRepository.save new Salary(person: personnelRepository.getOne(98L), salary: 138812)
        salaryRepository.save new Salary(person: personnelRepository.getOne(99L), salary: 125553)
        salaryRepository.save new Salary(person: personnelRepository.getOne(100L), salary: 118450)

    }

}
